### ISSUE TITLE
Enhance node status tracking and expand status dimensions for workers and APIs

### ISSUE THREAD

**Issue by pseudoyu** [RSS3-Network/Node#415]
### What feature is it?

1. need more status dimensions of node
2. need a status dashboard/static page for operators

### What problem does this feature solve?

We only have few node status monitoring and alerting data for operators.

### This is not a duplicated feature request or new worker proposal

- [X] I have searched [existing issues](https://github.com/rss3-network/node/issues) to ensure this feature has not already been requested and this is not a [New Worker](https://github.com/rss3-network/node/issues/new?assignees=&labels=worker&projects=&template=worker_coverage.yml).

**Comment by pseudoyu** [comment]
TODOs:

- [ ] current public address
- [ ] recent history records (GI heartbeat, requests, rewards, slashing, etc.)

**Comment by HenryQW** [comment]
- [ ] Node uptime
- [ ] Node coverage

**Comment by pseudoyu** [comment]
- [ ] index count
- [ ] indexing progress
- [ ] worker status
